### ISSUE TITLE
some problems about how to convert ccs bam to hifi bam

### ISSUE THREAD

**Issue by lhccc0909** [mihshimada/Brain_Iso-Seq#1]
Hi,
    I have read your paper "Identification of region-specific gene isoforms in the human brain using long-read transcriptome sequencing" and wanted to use the ccs data to repeat the Iso-Seq Analysis pipeline. I downloaded the data from SRA (the SRA ids are DRR481116 DRR481117 DRR481126 DRR481125 DRR481124 DRR481123 DRR481122 DRR481121 DRR481120) and converted them to fastq files. 
    I have also succesfully downloaded and installed the software SMRT Link you recommended in your paper. But I found the software SMRT Link can only recongnize subreads bam files or hifi bam files. So I want to know if there are any methods to convert ccs files to hifi files? 
    Thank you very much in advance!
![Snipaste_2024-03-31_11-21-00](https://github.com/mihshimada/Brain_Iso-Seq/assets/154948268/fec43f5c-a9de-4314-95c0-fcbea0bd8d94)

**Comment by mihshimada** [comment]
I uploaded the CCS BAM files directly, but it seems there might be an issue, so I will check on it. However, I am unable to verify this at the moment as the repository is currently under maintenance. I will contact you as soon as I am able to confirm the situation.

**Comment by lhccc0909** [comment]
Thank you for taking the time to reply amidst your busy schedule! I'll also explore other possible methods. Thanks once again!

**Comment by mihshimada** [comment]
I have confirmed that I indeed uploaded the BAM file, and there were no issues with the file. 
Could you please check the file loading procedure once again?
Thank you.
